Implement Strictly typed Tags
scsibug/nostr-rs-relay pull request #9
Opened 2022-01-18 10:47 UTC by rajarshimaitra

This is a first step of moving towards strictly typed structs and custom serde serilisation.

As discussed in https://github.com/scsibug/nostr-rs-relay/issues/5, this gives run time guarantees that json data are always correctly parsed into right type. Or else deserialisation will panic.

I started with the smallest custom json of prtocol messages, tags, and made a separate module to contain tags related codes.

The `Tag` is not used on other parts of the code currently. But it will compile and run the tests with `cargo test`.

Added all the possible json tag stream violation in tests. Each violation spits a helpful error message showing what exactly went wrong. 

More edge case suggestions are welcome.

2022-01-18 13:29 UTC, scsibug approved these changes
Looks reasonable and convenient.

2022-01-18 13:30 UTC, scsibug requested changes
The recommended relay is a URL, not a socket address.

2022-01-18 13:42 UTC, rajarshimaitra commented
> The recommended relay is a URL, not a socket address.

Ya I was thinking the same, but can the URL be built with a socket addrs? Haven't looked deeply at websockets, but I imagine the url would look something like `ws://<ip addrs>:<port>` so that should be buildable from a socket addrs?

2022-01-18 13:45 UTC, scsibug commented
Unfortunately no, we can't build a URL from the socket addr.  See the current public relay list here for a concrete example: https://nostr-registry.netlify.app/

`wss://freedom-relay.herokuapp.com/ws` is hosting a relay at a subdirectory, and that would not be representable with a SocketAddr.

2022-01-18 13:49 UTC, rajarshimaitra commented
Ah ok, so the socket address is being translated.

I think for this field should it be kept simple `String` or we want to deal with only up and valid websocket url internally? If we don't care weather the url should be responsive in a tag, we might not even care parsing it also. So we can just keep it as a String.

2022-01-18 13:52 UTC, scsibug commented
Agreed w/ using a String.  I think relays should be pretty permissive for stuff like this, if a client wants to sign events with a recommended relay that is not a valid URL, that is on them, but we should still handle their events.

2022-01-19 13:42 UTC, scsibug approved these changes
Looks good with the Option<String>.

2022-01-19 13:42 UTC, merged